# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# Created By LuXijun


class Ui_initWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1182, 686)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 569, 1111, 21))
        self.progressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(0,0 ,0 );\n"
"    border-style:none;\n"
"    border-radius:10px;\n"
"    color:rgb(255,0,0)\n"
"}\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread: pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(0,136, 255, 255), stop:1 rgba(255,255,255,255));\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 3)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1000, 600, 141, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.blackground = QtWidgets.QLabel(self.centralwidget)
        self.blackground.setGeometry(QtCore.QRect(20, 0, 1140, 644))
        #添加全地址
        self.blackground.setStyleSheet("border-image: url(C:/Users/HP/Desktop/_tiao/2022TZB-UI-main/2022tzb-ui/img/cover.jpg);\n"
"border-top-left-radius:30px;\n"
"border-top-right-radius:30px;\n"
"border-bottom-left-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.blackground.setText("")
        self.blackground.setObjectName("blackground")
        self.begin = QtWidgets.QPushButton(self.centralwidget)
        self.begin.setGeometry(QtCore.QRect(530, 600, 141, 41))
        self.begin.setStyleSheet("#begin{\n"
"border:2px solid rgb(255, 255, 255);\n"
"color:white;\n"
"font: 12pt \"微软雅黑\";\n"
"border-radius:10px;\n"
"}\n"
"#begin:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.begin.setObjectName("begin")
        self.blackground.raise_()
        self.progressBar.raise_()
        self.label.raise_()
        self.begin.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1182, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Initializing ..."))
        self.begin.setText(_translate("MainWindow", "开始"))
import resource_rc
